services:
  mongodb:
    image: mongo:latest
    restart: on-failure
    environment:
      # Creates an admin user used by 'app', credentials are found
      # in the .env file
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PWD}
    # We want to report to the 'app' service when the db is ready to use
    # because otherwise 'app' will attempt to connect using credentials
    # that eventually don't exist yet
    healthcheck:
      # Ping the database every 30th second, with a 10s interval
      test: ["CMD", "mongosh", "--eval", "'db.runCommand(\"ping\").ok'", "--quiet"]
      interval: 10s
      timeout: 10s
      # If not successful after 5 retries, 'app' will not start
      retries: 20

  setup-db:
    depends_on:
      mongodb:
        condition: service_healthy
    build:
      context: ./setup-db
      dockerfile: Dockerfile

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    working_dir: /app
    # We create two seperate volumes so that we don't encounter errors
    # in production where the node_modules folder may look different
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      setup-db:
        condition: service_completed_successfully
